name: publish
on:
    push:
        branches:
            - main
permissions:
    packages: write
    contents: read
jobs:
    publish-python2:
        runs-on: ubuntu-24.04
        steps:
            - uses: docker/setup-buildx-action@v3
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/superstormer/python2
            - uses: docker/build-push-action@v6
              with:
                  push: true
                  file: ./python2.Dockerfile
                  tags: ghcr.io/superstormer/python2,ghcr.io/superstormer/python2:sha-${{ github.sha }}
                  labels: ${{ steps.meta.outputs.labels }}
                  outputs: type=docker,dest=/tmp/image.tar
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: image
                  path: /tmp/image.tar
    publish-volatility2:
        runs-on: ubuntu-24.04
        needs: publish-python2
        steps:
            - uses: docker/setup-buildx-action@v3
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: image
                  path: /tmp

            - name: Load image
              run: |
                  docker load --input /tmp/image.tar
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/superstormer/volatility2
            - uses: docker/build-push-action@v6
              with:
                  push: true
                  file: ./volatility2.Dockerfile
                  tags: ghcr.io/superstormer/volatility2,ghcr.io/superstormer/volatility2:sha-${{ github.sha }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
