name: publish
on:
    push:
        branches:
            - main
permissions:
    packages: write
    contents: read
jobs:
    publish:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                image: [python2, volatility2]
            fail-fast: true
            max-parallel: 1
        steps:
            - uses: docker/setup-buildx-action@v3
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/superstormer/${{ matrix.image }}
            - uses: docker/build-push-action@v6
              with:
                  push: true
                  file: ./${{ matrix.image }}.Dockerfile
                  tags: ghcr.io/superstormer/${{ matrix.image }},ghcr.io/superstormer/${{ matrix.image }}:sha-${{ github.sha }}
                  labels: ${{ steps.meta.outputs.labels }}
                  outputs: type=docker,dest=/tmp/image.tar
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: image
                  path: /tmp/image.tar
